Mon Nov  1 07:55:16 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   31C    P0    41W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Master address: localhost
Master port: 1234
Number of nodes: 1
Number of GPUs per node: 1
Node rank: 0
Workspace: /project/def-karray/yafathi/MINE/
Dataset: kitti_raw
Version: debug
Extra config: {"training.gpus": "0"}
default params: ./configs/params_kitti_raw.yaml
Dumping extra config file...
[2021-11-01 07:55:57,815 train.py] Training config: {'data.img_h': 128, 'data.img_w': 384, 'data.name': 'kitti_raw', 'data.num_seq_per_gpu': 4, 'data.per_gpu_batch_size': 4, 'data.num_tgt_views': 1, 'data.training_set_path': 'kitti_raw_data', 'data.val_set_path': 'kitti_raw_data', 'data.num_workers': 4, 'lr.backbone_lr': 0.001, 'lr.decay_gamma': 0.1, 'lr.decay_steps': [40, 80, 100], 'lr.decoder_lr': 0.001, 'lr.weight_decay': 4e-05, 'model.backbone_normalization': True, 'model.decoder_normalization': True, 'model.pos_encoding_multires': 10, 'model.imagenet_pretrained': True, 'mpi.disparity_end': 0.001, 'mpi.disparity_start': 0.2, 'mpi.is_bg_depth_inf': False, 'mpi.num_bins_coarse': 32, 'mpi.num_bins_fine': 0, 'mpi.valid_mask_threshold': 2, 'mpi.fix_disparity': False, 'mpi.use_alpha': False, 'loss.smoothness_lambda_v1': 0.0, 'loss.smoothness_gmin': 2.0, 'loss.smoothness_grad_ratio': 0.1, 'loss.smoothness_lambda_v2': 0.01, 'training.epochs': 120, 'training.eval_interval': 2000, 'training.fine_tune': False, 'training.gpus': [0], 'training.pretrained_checkpoint_path': None, 'training.sample_interval': 30, 'training.src_rgb_blending': True, 'training.use_multi_scale': True, 'testing.frames_apart': 'random', 'current_epoch': 0, 'global_rank': 0, 'local_workspace': '/project/def-karray/yafathi/MINE/debug', 'local_rank': 0, 'world_size': 1, 'log_file': '/project/def-karray/yafathi/MINE/debug/training.log'}
/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torchvision/transforms/transforms.py:257: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
[2021-11-01 07:55:58,060 nerf_dataset.py] Dataset root: kitti_raw_data, is_validation: False, number of images: 5989
[2021-11-01 07:55:58,109 nerf_dataset.py] Dataset root: kitti_raw_data, is_validation: True, number of images: 1242
num_ch_enc= [  64  256  512 1024 2048]
upconv_4_0 2069 256
upconv_4_1 1301 256
upconv_3_0 256 128
upconv_3_1 661 128
upconv_2_0 128 64
upconv_2_1 341 64
upconv_1_0 64 32
upconv_1_1 117 32
upconv_0_0 32 16
upconv_0_1 16 16
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/lpips/weights/v0.1/vgg.pth
[2021-11-01 07:56:02,156 utils.py] Not using pre-trained model...
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    main()
  File "train.py", line 177, in main
    train()
  File "train.py", line 163, in train
    synthesis_task.train(train_data_loader, val_data_loader)
  File "/project/6006191/yafathi/MINE/synthesis_task_kitti.py", line 652, in train
    self.train_epoch(train_data_loader, val_data_loader, epoch)
  File "/project/6006191/yafathi/MINE/synthesis_task_kitti.py", line 592, in train_epoch
    for step, items in enumerate(train_data_loader):
  File "/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/project/6006191/yafathi/MINE/input_pipelines/kitti_raw/nerf_dataset.py", line 151, in __getitem__
    img_src, img_trg, k_s, k_t, rot, trans_ = self.get_data(img_src,img_tgt,(img_src_size[1],img_src_size[0]),(img_tgt_size[1],img_tgt_size[0]),calib_data)
  File "/project/6006191/yafathi/MINE/input_pipelines/kitti_raw/nerf_dataset.py", line 120, in get_data
    k_s = np.copy(calib_data['P_rect_02'].reshape(3, 4)[:3, :3])
ValueError: cannot reshape array of size 1 into shape (3,4)
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/project/6006191/yafathi/MINE_ENV/bin/python3', '-u', 'train.py', '--local_rank=0', '--config_path', './configs/params_kitti_raw.yaml', '--workspace', '/project/def-karray/yafathi/MINE/', '--version', 'debug', '--extra_config', '{"training.gpus": "0"}']' returned non-zero exit status 1.
Killing subprocess 172839
